### PR TITLE
Fixed Postmark gem issues reported

### PR DESCRIPTION
**Pull request by ibalosh**
Hi @tomazy 

when you have some time, could you check out this branch? It contains fixes for issues users reported:

- Inflector issue (you could not use symbols if hash container sub-objects like hash or aray)- https://github.com/wildbit/postmark-gem/issues/94
- Email addresses issue - https://github.com/wildbit/postmark-gem/issues/95
- Archive message stream endpoints - https://github.com/wildbit/postmark-rails/issues/80

### CODE REVIEW

**Comment by ibalosh** [comment]
hold on on this one, need to fix something

**Comment by tomazy** [comment]
@ibalosh would you mind splitting this PR into individual ones please? I'm afraid we may need to bump the major version number for the changes to the HashHelper.

**Comment by ibalosh** [comment]
Hey @tomazy good point, will separate it out and fix the remaining test failures.

**Comment by ibalosh** [comment]
hey @tomazy 

separated out all the updates and fixed the tests. Will send PR for hash helper later today. It works but I am looking if I could make it less intrusive.

**Pull request closed without merging**
