### PR TITLE
Remove deprecated trigger update endpoint references, update to v1.20.0

### PR DESCRIPTION
**Pull request by nickhammond**

### CODE REVIEW

**Comment by ibalosh** [comment]
looks good to me

(first I was wondering why only update is deprecated, but then realized we use other endpoints for inbound rules)

**Comment by nickhammond** [comment]
@ibalosh Yah, create and delete still exist but now the create is a unique creation. I am wondering if we foresee adding in any other types of triggers that would need an update. We can always leave it in place just in case but I'd also rather not leave around dead code.

**Comment by ibalosh** [comment]
got it, my guess is that we would not be adding any new triggers. Lets leave it though, and we will see how it goes, its a simple change

**Comment by atheken** [comment]
Given our shift towards message streams, it is more likely that the inbound trigger api will move to some sort of configuration api for an inbound stream. (It’s not really even a “trigger“ as much as it is a filter..)

**Comment by ibalosh** [comment]
for now I think we just need to move the updates out, it's small enough to not be worth to mangle more around it, things are starting to queue up

**Pull request merged**
